const DISPUTE_ACCOUNT = "DISPUTE_ACCOUNT"
const VIOLATION_COUNT = "VIOLATION_COUNT"
const LOCATION = "LOCATION"
const NAME = "NAME"
const PHONE = "PHONE"
const EMAIL = "EMAIL"
const PARKING_ADMIN_ID = "PARKING_ADMIN_ID"
const TOWN_MANAGER_ID = "TOWN_MANAGER_ID"
const STATUS = "STATUS"

export {
  DISPUTE_ACCOUNT,
  VIOLATION_COUNT,
  LOCATION,
  NAME,
  PHONE,
  EMAIL,
  PARKING_ADMIN_ID,
  TOWN_MANAGER_ID,
  STATUS
};