const STREAM_PERMISSION = 'STREAM_PERMISSION'
const STREAM_NAME = 'STREAM_NAME'
const DELETE_STREAM = 'DELETE_STREAM'
const STREAM_TRANSMISSION = 'STREAM_TRANSMISSION'

export {
  STREAM_TRANSMISSION,
  STREAM_NAME,
  STREAM_PERMISSION,
  DELETE_STREAM
}